--@Autor: Benítez Pérez Michelle Paulina
--        Hernández García Pilar Jaqueline
--@Fecha creación: 08/12/2025
--@Descripción: 

connect infra_admin/infra_admin@pf_infraestr

-- 
-- TABLE: APARATO 
--

CREATE TABLE APARATO(
    APARATO_ID           NUMBER(10, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA_STATUS         DATE             NOT NULL,
    NUMERO_INVENTARIO    VARCHAR2(18)     NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    FECHA_ADQUISICION    DATE             NOT NULL,
    DESCRIPCION          VARCHAR2(200)    NOT NULL,
    SALA_ID              NUMBER(7, 0)     NOT NULL,
    TIPO_APARATO_ID      NUMBER(4, 0)     NOT NULL,
    STATUS_APARATO_ID    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT APARATO_PK PRIMARY KEY (APARATO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT APARATO_FECHAS_CHK CHECK (FECHA_STATUS >= FECHA_ADQUISICION)
) TABLESPACE infra_c1_data_ts;

-- 
-- TABLE: ARCHIVO_MULTIMEDIA 
--

CREATE TABLE ARCHIVO_MULTIMEDIA(
    ARCHIVO_ID            NUMBER(6, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    ARCHIVO_MULTIMEDIA    BLOB            NOT NULL,
    FECHA_INICIO          DATE            NOT NULL,
    FECHA_FIN             DATE            NOT NULL,
    GIMNASIO_ID           NUMBER(4, 0)    NOT NULL,
    CONSTRAINT ARCHIVO_PK PRIMARY KEY (ARCHIVO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT ARCHIVO_FECHAS_CHK CHECK (FECHA_FIN >= FECHA_INICIO)
) TABLESPACE infra_c1_data_ts
LOB (ARCHIVO_MULTIMEDIA) STORE AS SECUREFILE
archivo_multimedia_lob (
    TABLESPACE infra_c2_lob_ts
    INDEX archivo_multimedia_lob_idx (TABLESPACE infra_c1_ix_ts)
);

-- 
-- TABLE: DISCIPLINA 
--

CREATE TABLE DISCIPLINA(
    DISCIPLINA_ID    NUMBER(6, 0)     GENERATED ALWAYS AS IDENTITY NOT NULL,
    CLAVE            VARCHAR2(5)      NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(200)    NOT NULL,
    ICONO            BLOB             NOT NULL,
    CONSTRAINT DISCIPLINA_PK PRIMARY KEY (DISCIPLINA_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts
LOB (ICONO) STORE AS SECUREFILE
disciplina_icono_lob (
    TABLESPACE infra_c1_lob_ts
    INDEX disciplina_icono_lob_idx (TABLESPACE infra_c1_ix_ts)
);

-- 
-- TABLE: GIMNASIO 
--

CREATE TABLE GIMNASIO(
    GIMNASIO_ID              NUMBER(4, 0)     GENERATED ALWAYS AS IDENTITY NOT NULL,
    FOLIO                    VARCHAR2(5)      NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    DIRECCION                VARCHAR2(200)    NOT NULL,
    LATITUD                  NUMBER(18, 6)    NOT NULL,
    LONGITUD                 NUMBER(18, 6)    NOT NULL,
    TEL_PRINCIPAL            VARCHAR2(10)     NOT NULL,
    PAGINA_WEB               VARCHAR2(500)    NOT NULL,
    EMPLEADO_GERENTE_RID     NUMBER(8, 0)     NOT NULL,
    CONSTRAINT GYM_PK PRIMARY KEY (GIMNASIO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT GIMNASIO_TEL_PRINCIPAL_UK UNIQUE (TEL_PRINCIPAL)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts;

-- 
-- TABLE: HISTORIAL_STATUS_APARATO 
--

CREATE TABLE HISTORIAL_STATUS_APARATO(
    HISTORIAL_STATUS_APARATO_ID    NUMBER(12, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA_STATUS                   DATE             NOT NULL,
    STATUS_APARATO_ID              NUMBER(1, 0)     NOT NULL,
    APARATO_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORIAL_STATUS_PK PRIMARY KEY (HISTORIAL_STATUS_APARATO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c2_hist_ts;

-- 
-- TABLE: SALA 
--

CREATE TABLE SALA(
    SALA_ID                      NUMBER(7, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    CLAVE                        VARCHAR2(3)     NOT NULL,
    NOMBRE                       VARCHAR2(40)    NOT NULL,
    CAPACIDAD_MAXIMA             NUMBER(3, 0)    NOT NULL,
    GIMNASIO_ID                  NUMBER(4, 0)    NOT NULL,
    EMPLEADO_RESPONSABLE_RID     NUMBER(8, 0)    NOT NULL,
    CONSTRAINT SALA_PK PRIMARY KEY (SALA_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT SALA_CLAVE_UK UNIQUE (CLAVE)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts;

-- 
-- TABLE: SALA_DISCIPLINA 
--

CREATE TABLE SALA_DISCIPLINA(
    SALA_DISCIPLINA_ID    NUMBER(8, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    DISCIPLINA_ID         NUMBER(6, 0)    NOT NULL,
    SALA_ID               NUMBER(7, 0)    NOT NULL,
    CONSTRAINT SALA_DISCIPLINA_PK PRIMARY KEY (SALA_DISCIPLINA_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT SALA_DISCIPLINA_DISC_ID_SALA_ID_UK UNIQUE (DISCIPLINA_ID, SALA_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts;

-- 
-- TABLE: STATUS_APARATO 
--

CREATE TABLE STATUS_APARATO(
    STATUS_APARATO_ID    NUMBER(1, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    DESCRIPCION          VARCHAR2(40)    NOT NULL,
    NOMBRE_STATUS        VARCHAR2(12)    NOT NULL
                         CONSTRAINT NOMBRE_STATUS_CHK CHECK (NOMBRE_STATUS IN ('VIGENTE','OBSOLETO','AVERIADO','EN REPARACION','FUERA DE USO')),
    CONSTRAINT STATUS_APARATO_PK PRIMARY KEY (STATUS_APARATO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT STATUS_APARATO_NOMBRE_STATUS_UK UNIQUE (NOMBRE_STATUS)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts;

-- 
-- TABLE: TIPO_APARATO 
--

CREATE TABLE TIPO_APARATO(
    TIPO_APARATO_ID    NUMBER(4, 0)    GENERATED ALWAYS AS IDENTITY NOT NULL,
    DESCRIPCION        VARCHAR2(40)    NOT NULL,
    NOMBRE_TIPO        VARCHAR2(40)    NOT NULL,
    CONSTRAINT TIPO_APARATO_PK PRIMARY KEY (TIPO_APARATO_ID)
    USING INDEX TABLESPACE infra_c1_ix_ts,
    CONSTRAINT TIPO_APARATO_NOMBRE_TIPO_UK UNIQUE (NOMBRE_TIPO)
    USING INDEX TABLESPACE infra_c1_ix_ts
) TABLESPACE infra_c1_data_ts;

-- 
-- FOREIGN KEYS
-- 

-- TABLE: APARATO
ALTER TABLE APARATO ADD CONSTRAINT APARATO_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES SALA(SALA_ID);

ALTER TABLE APARATO ADD CONSTRAINT APARATO_TIPO_APARATO_ID_FK 
    FOREIGN KEY (TIPO_APARATO_ID)
    REFERENCES TIPO_APARATO(TIPO_APARATO_ID);

ALTER TABLE APARATO ADD CONSTRAINT APARATO_STATUS_APARATO_ID_FK 
    FOREIGN KEY (STATUS_APARATO_ID)
    REFERENCES STATUS_APARATO(STATUS_APARATO_ID);

-- TABLE: ARCHIVO_MULTIMEDIA
ALTER TABLE ARCHIVO_MULTIMEDIA ADD CONSTRAINT ARCHIVO_MULTIMEDIA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO(GIMNASIO_ID);

-- TABLE: HISTORIAL_STATUS_APARATO
ALTER TABLE HISTORIAL_STATUS_APARATO ADD CONSTRAINT HISTORIAL_STATUS_APARATO_STATUS_APARATO_ID_FK 
    FOREIGN KEY (STATUS_APARATO_ID)
    REFERENCES STATUS_APARATO(STATUS_APARATO_ID);

ALTER TABLE HISTORIAL_STATUS_APARATO ADD CONSTRAINT HISTORIAL_STATUS_APARATO_APARATO_ID_FK 
    FOREIGN KEY (APARATO_ID)
    REFERENCES APARATO(APARATO_ID);

-- TABLE: SALA
ALTER TABLE SALA ADD CONSTRAINT SALA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO(GIMNASIO_ID);

-- TABLE: SALA_DISCIPLINA
ALTER TABLE SALA_DISCIPLINA ADD CONSTRAINT SALA_DISCIPLINA_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES SALA(SALA_ID);

ALTER TABLE SALA_DISCIPLINA ADD CONSTRAINT SALA_DISCIPLINA_DISCIPLINA_ID_FK 
    FOREIGN KEY (DISCIPLINA_ID)
    REFERENCES DISCIPLINA(DISCIPLINA_ID);