--@Autor: Benítez Pérez Michelle Paulina
--        Hernández García Pilar Jaqueline
--@Fecha creación: 08/12/2025
--@Descripción: 

connect infra_admin/infra_admin@pf_infraestr


-- 
-- ÍNDICES NO ÚNICOS, DE LAS FK
-- 

CREATE INDEX APARATO_SALA_ID_IX ON APARATO(SALA_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX APARATO_TIPO_APARATO_ID_IX ON APARATO(TIPO_APARATO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX APARATO_STATUS_APARATO_ID_IX ON APARATO(STATUS_APARATO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX ARCHIVO_MULTIMEDIA_GIMNASIO_ID_IX ON ARCHIVO_MULTIMEDIA(GIMNASIO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX GIMNASIO_EMPLEADO_GERENTE_ID_IX ON GIMNASIO(EMPLEADO_GERENTE_RID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX HISTORIAL_STATUS_APARATO_STATUS_APARATO_ID_IX ON HISTORIAL_STATUS_APARATO(STATUS_APARATO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX HISTORIAL_STATUS_APARATO_APARATO_ID_IX ON HISTORIAL_STATUS_APARATO(APARATO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX SALA_GIMNASIO_ID_IX ON SALA(GIMNASIO_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX SALA_EMPLEADO_RESPONSABLE_ID_IX ON SALA(EMPLEADO_RESPONSABLE_RID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX SALA_DISCIPLINA_SALA_ID_IX ON SALA_DISCIPLINA(SALA_ID)
TABLESPACE infra_c1_ix_ts;

CREATE INDEX SALA_DISCIPLINA_DISCIPLINA_ID_IX ON SALA_DISCIPLINA(DISCIPLINA_ID)
TABLESPACE infra_c1_ix_ts;
